version: "3.9"

services:
  backend-service:
    build:
      context: backend-service
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    depends_on:
      - postgres
  
  postgres:
    container_name: postgresql
    image: postgres:17.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devopsl-db

volumes:
  postgres:

