server:
  port: 1000

spring:
  application:
    name: BACKEND-SERVICE
  datasource:
#     url: jdbc:postgresql://localhost:5432/devopsl-db            # <-- local
     url: jdbc:postgresql://postgres:5432/devopsl-db     # <-- docker
     username: postgres
     password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 1000