apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
    prometheus.io/scrape: "true"
    prometheus.io/port: "32761"
    prometheus.io/path: "/metrics"
  labels:
    io.kompose.service: backend-service
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend-service
    spec:
      containers:
        - image: marmevladek/devopsl-backend:latest
          name: backend-service
          ports:
            - containerPort: 1000
              protocol: TCP
          resources:
            requests:
              cpu: "500m"     
              memory: "1Gi"  
            limits:
              cpu: "2"         
              memory: "2Gi"    
      restartPolicy: Always
