apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: notification-service
        image: marmevladek/devopsl-notification:latest
        ports:
        - containerPort: 1010
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 1010
      targetPort: 1010
  type: NodePort