apiVersion: v1
kind: Service
metadata:
  name: postgres  # DNS-имя, указанное в конфиге backend-service
  labels:
    io.kompose.service: postgres
spec:
  selector:
    io.kompose.service: postgres  # Должен совпадать с лейблами пода PostgreSQL
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432