name: Notification Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'notification-service/**'
      - '.github/workflows/notification-service.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'notification-service/**'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('notification-service/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devopsl -Dsonar.projectName='devopsl'

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Format code
        working-directory: notification-service
        run: mvn net.revelc.code.formatter:formatter-maven-plugin:2.24.1:format

      - name: Validate format
        working-directory: notification-service
        run: mvn formatter:validate

      - name: Test notification-service
        run: mvn test
        working-directory: notification-service

  docker-image:
    runs-on: ubuntu-latest
    name: Docker Image
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push notification Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            marmevladek/devopsl-notification:latest