name: Product Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend-service/**'
      - '.github/workflows/product-service.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend-service/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build product-service
        run: mvn clean install -DskipTests
        working-directory: backend-service

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Test backend-service
        run: mvn test
        working-directory: backend-service

  docker-image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-service
          file: ./backend-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            marmevladek/devopsl-backend:latest