name: Product Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend-service/**'
      - '.github/workflows/product-service.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Format code
        working-directory: backend-service
        run: mvn net.revelc.code.formatter:formatter-maven-plugin:2.24.1:format

      - name: Validate format
        working-directory: backend-service
        run: mvn formatter:validate

      - name: Build backend-service
        run: mvn clean install -DskipTests
        working-directory: backend-service

  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Format code
        working-directory: backend-service
        run: mvn net.revelc.code.formatter:formatter-maven-plugin:2.24.1:format

      - name: Validate format
        working-directory: backend-service
        run: mvn formatter:validate

      - name: Test backend-service
        run: mvn test
        working-directory: backend-service


  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Wait for SonarQube to be ready
        run: |
          for i in {1..20}; do
            curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"' && break
            echo "Waiting for SonarQube..."
            sleep 15
          done

      - name: Analyze backend-service
        working-directory: backend-service
        run: mvn verify sonar:sonar

  docker-image:
    runs-on: ubuntu-latest
    needs: sonar
    name: Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-service
          file: ./backend-service/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            marmevladek/devopsl-backend:latest